apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appservice-ingress
spec:
  rules:
  - host: k8s.local
    http:
      paths:

      - path: /logger/logs
        pathType: Prefix
        backend:
          service:
            name: logger-service
            port:
              number: 8080 # Porta do logger-service
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 8080 # Porta do app-service